### ISSUE TITLE
Feature Request: Add username variable

### ISSUE THREAD

**Issue by Phoenix616** [roflmuffin/fabric-title-changer#1]
This is a request to add a variable to show the username in the title. This would be useful for cases where you have mutliple clients open to test certain stuff or for specifying the right window for recording timelapses in recording programs that try to select windows based on the title (e.g. OBS)

**Comment by roflmuffin** [comment]
Hey mate, thanks for the request, I have added this in a [new version, 1.04 ](https://www.curseforge.com/minecraft/mc-mods/fabric-title-changer/files/3005556). When you are using the `overrideTitle `option, just put in `%username%` and it will get replaced with the logged in user's name.

Let me know if theres any issues.
